"""The uplc command line: check, fmt, unpack."""

from __future__ import annotations

import argparse
import os
import sys

from .emit_python import emit_python
from .emit_sql import emit_sql
from .emit_web import emit_web
from .model import BundleError, load
from .sexpr import ParseError, dumps, parse

VERSION = "0.1"


def _load_file(path: str):
    with open(path, "r", encoding="utf-8") as fh:
        return load(fh.read())


def _header(app, src_path: str) -> str:
    return (
        f"GENERATED BY uplc v{VERSION} FROM {os.path.basename(src_path)} — DO NOT EDIT.\n"
        f"Edit the bundle and re-run: python -m uplc unpack {os.path.basename(src_path)}\n"
        f"bundle sha256: {app.bundle_hash}"
    )


def cmd_check(args) -> int:
    app = _load_file(args.bundle)
    print(f"ok: {len(app.entities)} entities, {len(app.actions)} actions, {len(app.queries)} queries, {len(app.pages)} pages")
    print(f"bundle sha256: {app.bundle_hash}")
    return 0


def cmd_fmt(args) -> int:
    with open(args.bundle, "r", encoding="utf-8") as fh:
        text = fh.read()
    canonical = dumps(parse(text)) + "\n"
    if args.write:
        with open(args.bundle, "w", encoding="utf-8") as fh:
            fh.write(canonical)
        print(f"formatted {args.bundle}")
    else:
        sys.stdout.write(canonical)
    return 0


def cmd_unpack(args) -> int:
    app = _load_file(args.bundle)
    header = _header(app, args.bundle)
    out = args.out
    targets = {
        os.path.join(out, "server", "app.py"): emit_python(app, header),
        os.path.join(out, "web", "index.html"): emit_web(app, header),
        os.path.join(out, "db", "schema.sql"): emit_sql(app, header),
    }
    for path, content in targets.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        print(f"wrote {path}")
    print(f"bundle sha256: {app.bundle_hash}")
    print(f"run: python {os.path.join(out, 'server', 'app.py')}")
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="uplc", description="UPL bundle compiler: check, format, and unpack .upl bundles.")
    sub = parser.add_subparsers(dest="command", required=True)

    p_check = sub.add_parser("check", help="validate a bundle")
    p_check.add_argument("bundle")
    p_check.set_defaults(fn=cmd_check)

    p_fmt = sub.add_parser("fmt", help="print (or rewrite) the canonical form")
    p_fmt.add_argument("bundle")
    p_fmt.add_argument("--write", action="store_true", help="rewrite the file in place")
    p_fmt.set_defaults(fn=cmd_fmt)

    p_unpack = sub.add_parser("unpack", help="compile a bundle to server/web/db targets")
    p_unpack.add_argument("bundle")
    p_unpack.add_argument("-o", "--out", default="build", help="output directory (default: build)")
    p_unpack.set_defaults(fn=cmd_unpack)

    args = parser.parse_args(argv)
    try:
        return args.fn(args)
    except (BundleError, ParseError) as err:
        print(f"error: {err}", file=sys.stderr)
        return 1
    except FileNotFoundError as err:
        print(f"error: {err}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
